//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1shop12.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int WorkerID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int Count { get; set; }
    
        public virtual product product { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
